.TH t 1
.SH NAME
t \- manage your notes
.SH SYNOPSIS
.B t
[\fB\-l\fR]
[\fB\-c\fR \f\\'Title of your note'\fR]
[\fB\-e\fR \f\index\fR]

.SH DESCRIPTION
.B t
a simple utility to manage your notes using Markdown

.SH OPTIONS

.TP
.B \-l 
List all notes created by the modification date

.TP
.BR \fB\-c\fR \ 'Title\ of\ your\ note'
Create a new note using the title you specified or
generate one using the current time

.TP
.BR \-e \ \f\index\fR
Edit a note fetching by it's index where zero it's 
the most recent note

.SH LICENSE

t is licensed under GNU GPL v3. You can get yourself a copy on LICENSE file.

.SH AUTHORS

t is an free and open source project. It's being maintained by Pedro Lucas Porcellis <pedrolucasporcellis@gmail.com>
and hosted on https://git.sr.ht/~porcellis/t.
