.TH t 1 "21 March 2020" "" "General User Commands"
.SH NAME
\fBt \fP- The simplest note taker
.SH SYNOPSIS
.nf
.fam C
\fBt\fP <command>
.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
\fBt\fP manage notes for you using git and your editor of choice. It will
store notes at your home directory 'notes' folder. 
.SH COMMANDS
There's three commands avaiable for `\fBt\fP`. *Create*, *List* and *Edit*
.RS
.IP \(bu 3
create <Title>
.PP
.nf
.fam C
        It will use the supplied title to create a new note on your
        NOTE_DIR or will generate a title using the current date-time.
.fam T
.fi
.IP \(bu 3
list
.PP
.nf
.fam C
        List all notes by descending order
.fam T
.fi
.IP \(bu 3
edit <Index>
.PP
.nf
.fam C
        Edit a note by the giving index (by descending order). If no
        supplied index, will edit the last created note.
.fam T
.fi
.SH AUTHORS
`\fBt\fP` is maintained by Pedro Lucas Porcellis <porcellis@eletrotupi.com>
and you can get yourself a copy at https://git.sr.ht/~porcellis/\fBt\fP
.SH CONTRIBUTING
You can send patches, file bugs and discuss the project by sending an
email to <porcellis@eletrotupi.com>
